steps:
- name: hashicorp/terraform:0.11.14
  dir: deployments/app1/dev
  args:
  - init
- name: hashicorp/terraform:0.11.14
  dir: deployments/app1/dev
  args:
  - plan
  - -out=terraform.plan
- name: gcr.io/config-validator/terraform-validator
  entrypoint: "/bin/bash"
  args: ['-c', 'terraform show -json terraform.plan > terraform.json']
  dir: deployments/app1/dev
- name: gcr.io/config-validator/terraform-validator
  dir: deployments/app1/dev
  args:
  - validate
  - --tf-version
  - "0.12"
  - terraform.json
  - --policy-path=../../../policy-library/
  - --project
  - "example-infra"



